[tokens]
identifier = '[a-zA-Z_]([a-zA-Z0-9_])*'
int = '-?[0-9]+'
float = '{int}\.[0-9]+'
equals = '='

[grammar]
expression = 'arithmeticExpression ( ( "=" | ">" | "<" ) arithmeticExpression ) *'
arithmeticExpression = 'term ( ( "+" | "-" ) term ) *'
term = 'factor ( ( "*" | "/" ) factor ) *'
factor = '( "-" ) ? operand'
operand = 'int | float | identifier'