[tokens]
keyword = '(if|else)'
identifier = '[a-zA-Z_]([a-zA-Z0-9_])*'
int = '-?[0-9]+'
float = '{int}\.[0-9]+'
equals = '='

[grammar]
sentence = "<noun-phrase> <predicate>"
noun-phrase = "<article> <noun>"
article = "the | a | an"
noun = "cat | flower"
predicate = "jumps | blooms"
